/**
 * Hidden Edit tab — timeline video editor types.
 *
 * A single uploaded video is represented as an ordered list of Clips.
 * Each Clip is a "recipe" (source range + speed + reversed + crop + freeze)
 * rather than pre-rendered media — rendering only happens for preview of
 * reversed clips (cached) and for the final export.
 */

export interface CropBox {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface FreezeSpec {
  /** Timestamp (seconds) in the source video the freeze frame was captured from. */
  sourceTime: number;
  durationSeconds: number;
}

export interface Clip {
  id: string;
  /** Seconds into the uploaded source video (ignored for freeze clips). */
  sourceStart: number;
  sourceEnd: number;
  /** Playback speed multiplier — 1 = normal. */
  speed: number;
  reversed: boolean;
  crop?: CropBox;
  /** Present only for clips created by the Freeze operation. */
  freeze?: FreezeSpec;
  /** Set by Duplicate — points at the clip.id this clip was copied from. */
  originClipId?: string;
  /** Set on clips generated by Auto Build so re-running it doesn't cascade. */
  autoBuilt?: boolean;
}

/** Everything the FFmpeg worker needs to render one clip — a plain subset of Clip. */
export type ClipRenderSpec = Pick<
  Clip,
  'id' | 'sourceStart' | 'sourceEnd' | 'speed' | 'reversed' | 'crop' | 'freeze'
>;

export interface TimelineRenderProgress {
  phase: 'loading' | 'rendering' | 'concatenating' | 'complete' | 'error';
  currentClip: number;
  totalClips: number;
  percent: number;
  message?: string;
}

/** Minimum total duration (seconds) Auto Build extends a detected pair to. */
export const AUTO_BUILD_MIN_EXTRA_SECONDS = 5;

/** Fixed freeze-clip duration used by the Freeze operation. */
export const FREEZE_CLIP_DURATION_SECONDS = 3;

export function getClipDuration(clip: Clip): number {
  if (clip.freeze) {
    return Math.max(0, clip.freeze.durationSeconds);
  }
  const speed = clip.speed > 0 ? clip.speed : 1;
  return Math.max(0, (clip.sourceEnd - clip.sourceStart) / speed);
}

export function getTimelineDuration(clips: Clip[]): number {
  return clips.reduce((sum, clip) => sum + getClipDuration(clip), 0);
}

export function toClipRenderSpec(clip: Clip): ClipRenderSpec {
  return {
    id: clip.id,
    sourceStart: clip.sourceStart,
    sourceEnd: clip.sourceEnd,
    speed: clip.speed,
    reversed: clip.reversed,
    crop: clip.crop,
    freeze: clip.freeze,
  };
}
